<?php
/**
 * @author: cc_forever<1253705861@qq.com>
 * @day: 2020/7/23
 */
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * 菜单默认数据
 * Class MenusTableSeeder
 */
class MenusTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('menus')->insert([
            [
                'id' => 1,
                'name' => '系统管理',
                'parent_id' => 0,
                'routes' => '/systems',
                'page' => '/system',
                'icon' => 'nested',
                'menu' => 1,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 50,
            ],
            [
                'id' => 2,
                'name' => '管理员列表',
                'parent_id' => 1,
                'routes' => '/admins/list',
                'page' => '/admins',
                'icon' => '',
                'menu' => 1,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 3,
                'name' => '菜单列表',
                'parent_id' => 1,
                'routes' => '/menus/list',
                'page' => '/menus',
                'icon' => '',
                'menu' => 1,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 2,
            ],
            [
                'id' => 4,
                'name' => '规则列表',
                'parent_id' => 1,
                'routes' => '/rules/list',
                'page' => '/rules',
                'icon' => '',
                'menu' => 1,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 3,
            ],
            [
                'id' => 5,
                'name' => '管理员添加',
                'parent_id' => 1,
                'routes' => '/admins/insert',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 6,
                'name' => '管理员修改',
                'parent_id' => 1,
                'routes' => '/admins/update',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 7,
                'name' => '管理员删除',
                'parent_id' => 1,
                'routes' => '/admins/delete',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 8,
                'name' => '管理员信息',
                'parent_id' => 1,
                'routes' => '/admins/message',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 9,
                'name' => '菜单添加',
                'parent_id' => 1,
                'routes' => '/menus/insert',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 10,
                'name' => '菜单修改',
                'parent_id' => 1,
                'routes' => '/menus/update',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 11,
                'name' => '菜单删除',
                'parent_id' => 1,
                'routes' => '/menus/delete',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 12,
                'name' => '菜单信息',
                'parent_id' => 1,
                'routes' => '/menus/message',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 13,
                'name' => '规则添加',
                'parent_id' => 1,
                'routes' => '/rules/insert',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 14,
                'name' => '规则修改',
                'parent_id' => 1,
                'routes' => '/rules/update',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 15,
                'name' => '规则删除',
                'parent_id' => 1,
                'routes' => '/rules/delete',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
            [
                'id' => 16,
                'name' => '规则信息',
                'parent_id' => 1,
                'routes' => '/rules/message',
                'page' => '',
                'icon' => '',
                'menu' => 0,
                'is_del' => 0,
                'add_time' => time(),
                'sort' => 1,
            ],
        ]);
    }
}
